version: '3.1'
services:
  android9:
    privileged: true
    image: budtmo/docker-android-x86-9.0
    environment:
      DEVICE: Samsung Galaxy S9
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5550:5555"
    container_name: android9