version: '3.1'
services:
  android10:
    privileged: true
    image: budtmo/docker-android-x86-10.0
    environment:
      DEVICE: Samsung Galaxy S10
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5550:5555"
    container_name: android10