-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 22:59:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPRESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPRESAS` (
  `empresaId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cnpj` INT UNSIGNED NOT NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `nomeResponsavel` VARCHAR(45) NOT NULL,
  `telefonePrincipal` INT NOT NULL,
  `telefoneSecundario` INT NULL,
  `obraId` INT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  PRIMARY KEY (`empresaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBRAS` (
  `obraId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `telefonePrincipal` INT NOT NULL,
  `telefoneSecundario` INT NULL,
  `cno` BIGINT NULL,
  UNIQUE INDEX `id_UNIQUE` (`obraId` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`logradouro` ASC) ,
  PRIMARY KEY (`obraId`),
  UNIQUE INDEX `cno_UNIQUE` (`cno` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIOS` (
  `funcionarioId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `situacao` TINYINT NULL,
  `funcao` VARCHAR(20) NULL,
  `cpf` INT UNSIGNED NOT NULL,
  `nascimento` BIGINT UNSIGNED NULL,
  `rg` INT UNSIGNED NULL,
  `telfonePrincipal` INT UNSIGNED NULL,
  `telefoneSecundario` INT UNSIGNED NULL,
  `email` VARCHAR(45) NULL,
  `apelido` VARCHAR(20) NULL,
  `obraId` INT UNSIGNED NOT NULL,
  `empresaId` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  PRIMARY KEY (`funcionarioId`),
  INDEX `fk_FUNCIONARIOS_OBRAS1_idx` (`obraId` ASC) ,
  INDEX `fk_FUNCIONARIOS_EMPRESAS1_idx` (`empresaId` ASC) ,
  CONSTRAINT `fk_FUNCIONARIOS_OBRAS1`
    FOREIGN KEY (`obraId`)
    REFERENCES `mydb`.`OBRAS` (`obraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIOS_EMPRESAS1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`EMPRESAS` (`empresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPAMENTOS` (
  `equipamentoId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `situacao` TINYINT NULL,
  `funcao` VARCHAR(20) NULL,
  `numeracao` INT UNSIGNED NOT NULL,
  `fabricacaoData` BIGINT UNSIGNED NULL,
  `telfonePrincipal` INT UNSIGNED NULL,
  `telefoneSecundario` INT UNSIGNED NULL,
  `apelido` VARCHAR(20) NULL,
  `responsavel` VARCHAR(45) NULL,
  `empresaId` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`numeracao` ASC) ,
  UNIQUE INDEX `matricula_UNIQUE` (`equipamentoId` ASC) ,
  PRIMARY KEY (`equipamentoId`),
  INDEX `fk_EQUIPAMENTOS_EMPRESAS1_idx` (`empresaId` ASC) ,
  CONSTRAINT `fk_EQUIPAMENTOS_EMPRESAS1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`EMPRESAS` (`empresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBRAS_EMPRESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBRAS_EMPRESAS` (
  `obraId` INT UNSIGNED NOT NULL,
  `empresaId` INT UNSIGNED NOT NULL,
  `situacao` TINYINT NULL,
  PRIMARY KEY (`obraId`, `empresaId`),
  INDEX `fk_OBRAS_has_EMPRESAS_EMPRESAS1_idx` (`empresaId` ASC) ,
  INDEX `fk_OBRAS_has_EMPRESAS_OBRAS1_idx` (`obraId` ASC) ,
  CONSTRAINT `fk_OBRAS_has_EMPRESAS_OBRAS1`
    FOREIGN KEY (`obraId`)
    REFERENCES `mydb`.`OBRAS` (`obraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OBRAS_has_EMPRESAS_EMPRESAS1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`EMPRESAS` (`empresaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FRENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FRENTES` (
  `frenteId` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL,
  `localizacao` VARCHAR(20) NULL,
  `obraId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`frenteId`),
  INDEX `fk_frente_OBRAS1_idx` (`obraId` ASC) ,
  CONSTRAINT `fk_frente_OBRAS1`
    FOREIGN KEY (`obraId`)
    REFERENCES `mydb`.`OBRAS` (`obraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RDO_FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RDO_FUNCIONARIOS` (
  `rdoId` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `dataInicio` BIGINT NULL,
  `dataFinal` BIGINT NULL,
  `obraId` INT UNSIGNED NOT NULL,
  `frenteId` INT NOT NULL,
  `funcionarioId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rdoId`),
  INDEX `fk_RDO_FUNCIONARIOS_OBRAS1_idx` (`obraId` ASC) ,
  INDEX `fk_RDO_FUNCIONARIOS_frente1_idx` (`frenteId` ASC) ,
  INDEX `fk_RDO_FUNCIONARIOS_FUNCIONARIOS1_idx` (`funcionarioId` ASC) ,
  CONSTRAINT `fk_RDO_FUNCIONARIOS_OBRAS1`
    FOREIGN KEY (`obraId`)
    REFERENCES `mydb`.`OBRAS` (`obraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDO_FUNCIONARIOS_frente1`
    FOREIGN KEY (`frenteId`)
    REFERENCES `mydb`.`FRENTES` (`frenteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDO_FUNCIONARIOS_FUNCIONARIOS1`
    FOREIGN KEY (`funcionarioId`)
    REFERENCES `mydb`.`FUNCIONARIOS` (`funcionarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RDO_EQUIPAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RDO_EQUIPAMENTOS` (
  `rdoId` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `dataInicio` BIGINT NULL,
  `dataFinal` BIGINT NULL,
  `horimetroInicio` BIGINT NULL,
  `horimetroFinal` BIGINT NULL,
  `obraId` INT UNSIGNED NOT NULL,
  `frenteId` INT NOT NULL,
  `equipamentoId` INT UNSIGNED NOT NULL,
  `funcionarioId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rdoId`, `equipamentoId`, `funcionarioId`),
  INDEX `fk_RDO_FUNCIONARIOS_OBRAS1_idx` (`obraId` ASC) ,
  INDEX `fk_RDO_FUNCIONARIOS_frente1_idx` (`frenteId` ASC) ,
  INDEX `fk_RDO_EQUIPAMENTO_EQUIPAMENTOS1_idx` (`equipamentoId` ASC) ,
  INDEX `fk_RDO_EQUIPAMENTO_FUNCIONARIOS1_idx` (`funcionarioId` ASC) ,
  CONSTRAINT `fk_RDO_FUNCIONARIOS_OBRAS10`
    FOREIGN KEY (`obraId`)
    REFERENCES `mydb`.`OBRAS` (`obraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDO_FUNCIONARIOS_frente10`
    FOREIGN KEY (`frenteId`)
    REFERENCES `mydb`.`FRENTES` (`frenteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDO_EQUIPAMENTO_EQUIPAMENTOS1`
    FOREIGN KEY (`equipamentoId`)
    REFERENCES `mydb`.`EQUIPAMENTOS` (`equipamentoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RDO_EQUIPAMENTO_FUNCIONARIOS1`
    FOREIGN KEY (`funcionarioId`)
    REFERENCES `mydb`.`FUNCIONARIOS` (`funcionarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
