export const funcao = [
	'Almoxarife',
	'Analista contábil',
	'Analista de recursos humanos',
	'Analista de sistemas júnior',
	'Analista financeiro',
	'Apontador de produção',
	'Armador',
	'Arquiteto',
	'Assistente administrativo',
	'Assistente comercial',
	'Assistente de contabilidade',
	'Assistente de pessoal',
	'Assistente financeiro',
	'Auxiliar administrativo',
	'Auxiliar de escritório',
	'Auxiliar de logística e suprimentos',
	'Carpinteiro',
	'Chefe de contabilidade geral',
	'Chefe de logística e suprimentos',
	'Chefe de pessoal',
	'Comprador júnior',
	'Comprador pleno',
	'Comprador sênior',
	'Coordenador obras',
	'Copeiro',
	'Desenhista projetista',
	'Eletricista manut. oficial',
	'Encarregado de carpintaria',
	'Encarregado de manutenção mecânica',
	'Encarregado de obras',
	'Encarregado de transporte',
	'Encarregado de turno',
	'Engenheiro civil júnior',
	'Engenheiro civil pleno',
	'Engenheiro civil sênior',
	'Engenheiro de segurança do trabalho',
	'Faxineiro',
	'Gerente administrativo',
	'Gerente de controladoria',
	'Gerente de logística e suprimentos',
	'Gerente de recursos humanos',
	'Mecânico de manutenção meio oficial',
	'Mecânico de manutenção oficial',
	'Mestre de obras',
	'Montador',
	'Motorista caminhão e carro leve',
	'Motorista de caminhão e carreta',
	'Operador de equipamento movimentação',
	'Operador de máquinas de produção',
	'Pedreiro construção',
	'Pintor manutenção',
	'Recepcionista',
	'Secretária diretoria bilíngue',
	'Secretária diretoria português',
	'Secretária júnior',
	'Servente de obras',
	'Soldador',
	'Técnico em edificações',
	'Técnico em segurança do trabalho',
	'Topógrafo',
	'Vigia',
];
