import Header from '@/component/header'
import Head from 'next/head'
import styles from './index.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react';


export default function Home() {
const [isData, setData] = useState(null)

useEffect(() => {
  fetch("/api/languages")
  .then(data=>data.json())
  .then((data)=>setData(data))
},[])

async function Delete(id){
    console.log(id)
    const request = await fetch(`/api/delete/${id}`,{
      method: "POST",
      body: JSON.stringify({id})
    }
  )
  setData(isData.filter(item=>item.id != id))
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
     {isData && isData.reverse().map(item=>(
      <div key={item.id} className={styles.card}>
        <h1>{item.title.toUpperCase()}</h1>
        <img src={item.image} 
        onError={(e)=> e.target.src = "http://wallpaperset.com/w/full/a/2/4/462748.jpg"}
        />
        <div className={styles.containerDescription}>
          <div>
          <h3>XP: {item.description}</h3>
          <h3>Stars: {"⭐".repeat(item.ranking)} </h3>
          <h3>Author: {item.origin}</h3>
          </div>   
          <div>
          <button type="button" >
            <Link href={`/add-update/${item.id}`}>
              <img src={"https://cdn-icons-png.flaticon.com/512/1827/1827951.png"}/>
            </Link>
          </button>
          <button type="button" onClick={()=> Delete(item.id)}>
            <img src={"https://cdn-icons-png.flaticon.com/512/2891/2891491.png"}/>
          </button>    
            </div>     
        </div>
        
        
      </div>
     ))}
      </main>
    </>
  )
}
