export const teamNames = [
  '-',
  'Botafogo',
  'Atlético-MG',
  'Grêmio',
  'Fluminense',
  'Palmeiras',
  'Atlético PR',
  'São Paulo',
  'Fortaleza',
  'Flamengo',
  'Cruzeiro',
  'Red Bull Bragantino',
  'Santos',
  'Internacional',
  'Bahia',
  'Corinthians',
  'Cuiabá-MT',
  'Goiás',
  'América-MG',
  'Vasco da Gama',
  'Coritiba',
];
export const teamIcons = [
  '-',
  {name: 'Botafogo', imagePath: require('../../public/teams/Botafogo.png')},
  {
    name: 'Atlético-MG',
    imagePath: require('../../public/teams/Atlético-MG.png'),
  },
  {name: 'Grêmio', imagePath: require('../../public/teams/Grêmio.png')},
  {name: 'Fluminense', imagePath: require('../../public/teams/Fluminense.png')},
  {name: 'Palmeiras', imagePath: require('../../public/teams/Palmeiras.png')},
  {
    name: 'Atlético PR',
    imagePath: require('../../public/teams/Atlético-PR.png'),
  },
  {name: 'São Paulo', imagePath: require('../../public/teams/São-Paulo.png')},
  {name: 'Fortaleza', imagePath: require('../../public/teams/Fortaleza.png')},
  {name: 'Flamengo', imagePath: require('../../public/teams/Flamengo.png')},
  {name: 'Cruzeiro', imagePath: require('../../public/teams/Cruzeiro.png')},
  {
    name: 'Red Bull Bragantino',
    imagePath: require('../../public/teams/Red-Bull-Bragantino.png'),
  },
  {name: 'Santos', imagePath: require('../../public/teams/Santos.png')},
  {
    name: 'Internacional',
    imagePath: require('../../public/teams/Internacional.png'),
  },
  {name: 'Bahia', imagePath: require('../../public/teams/Bahia.png')},
  {
    name: 'Corinthians',
    imagePath: require('../../public/teams/Corinthians.png'),
  },
  {name: 'Cuiabá-MT', imagePath: require('../../public/teams/Cuiabá-MT.png')},
  {name: 'Goiás', imagePath: require('../../public/teams/Goiás.png')},
  {name: 'América-MG', imagePath: require('../../public/teams/América-MG.png')},
  {
    name: 'Vasco da Gama',
    imagePath: require('../../public/teams/Vasco-da-Gama.png'),
  },
  {name: 'Coritiba', imagePath: require('../../public/teams/Coritiba.png')},
];

export const stadiums = [
  '-',
  'Estádio Jornalista Mário Filho',
  'Neo Química Arena',
  'Estádio Urbano Caldeira',
  'Estádio São Januário',
  'Estádio Raimundo Sampaio',
  'Estádio Olímpico Nilton Santos',
  'Estádio Nabi Abi Chedid',
  'Estádio Major Antônio Couto Pereira',
  'Estádio Governador Plácido Castelo',
  'Estádio Governador Magalhães Pinto',
  'Estádio de Hailé Pinheiro',
  'Estádio Cícero Pompeu de Toledo',
  'Estádio Beira-Rio',
  'Arena Pantanal',
  'Arena Fonte Nova',
  'Arena do Grêmio',
  'Arena da Baixada',
  'Allianz Parque',
];
